server:
  port: 9000

spring:
  datasource:
    url: ${databaseUrl}
    driver-class-name: org.postgresql.Driver
    username: ${databaseUser}
    password: ${databasePassword}
  jooq:
    sql-dialect: postgres
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
    default-schema: security

logging:
  level:
    org.jooq: INFO
    org.springframework.security: INFO
