server:
  port: 9000

spring:
  datasource:
    url: jdbc:h2:mem:security;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jooq:
    sql-dialect: h2
  liquibase:
    change-log: classpath:db/changelog/db.changelog.xml
  h2:
    console:
      enabled: true

logging:
  level:
    org.jooq: INFO
    org.springframework.security: INFO
